# firefox.manifest.yaml
name: Firefox
version: "123.0"
url: "https://download-installer.cdn.mozilla.net/pub/firefox/releases/123.0/mac/en-US/Firefox%20123.0.dmg"
filename: "Firefox-123.0.dmg"
checksum: "80321c06df972dcf7d346d1137ca0d31be8988fdcf892702da77a43f4bb8a8f1"
code_sign:
  team_id: "43AQ936H96"  # Mozilla's Team ID
  require_notarized: true
build:
  type: "app_dmg"
  destination: "/Applications"
  preserve_temp: false
  sign:
    identity: "Developer ID Installer: Your Company (XXXXXXXXXX)"  # Optional, for re-signing