# ruff.toml
line-length = 100
target-version = "py311"

[lint]
select = [
    "E", # pycodestyle errors
    "F", # pyflakes
    "I", # isort
    "B", # flake8-bugbear
    "S", # flake8-bandit
]
ignore = [
    "E501", # Line too long (temporarily)
    "S101", # Use of assert (allow in tests)
]
[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
